language: python
python:
  - '3.6'
  - '2.7'
env:
  - PI=raspberry-pi
  - PI=raspberrypi3
      
services:
  - docker

script:
  - docker build --build-arg pi=${PI} --build-arg python=${TRAVIS_PYTHON_VERSION} -t testingtony/balena-inky-phat:temp .

deploy:
  - provider: script
    script: bash docker_push temp ${PI}-${TRAVIS_PYTHON_VERSION}-${TRAVIS_BRANCH}
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master

  - provider: script
    script: bash docker_push temp ${PI}-${TRAVIS_PYTHON_VERSION}
    on:
      branch: master

  - provider: script
    script: bash docker_push temp ${PI}
    on:
      branch: master
      condition: ${TRAVIS_PYTHON_VERSION:0:1} == 3
      
